/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { GraphQLUpload } from "graphql-upload";
import { FileUpload } from "src/storage/base/storage.types";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { EbookMarketing } from "./EbookMarketing";
import { EbookMarketingCountArgs } from "./EbookMarketingCountArgs";
import { EbookMarketingFindManyArgs } from "./EbookMarketingFindManyArgs";
import { EbookMarketingFindUniqueArgs } from "./EbookMarketingFindUniqueArgs";
import { CreateEbookMarketingArgs } from "./CreateEbookMarketingArgs";
import { UpdateEbookMarketingArgs } from "./UpdateEbookMarketingArgs";
import { DeleteEbookMarketingArgs } from "./DeleteEbookMarketingArgs";
import { EbookMarketingService } from "../ebookMarketing.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => EbookMarketing)
export class EbookMarketingResolverBase {
  constructor(
    protected readonly service: EbookMarketingService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "EbookMarketing",
    action: "read",
    possession: "any",
  })
  async _ebookMarketingsMeta(
    @graphql.Args() args: EbookMarketingCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [EbookMarketing])
  @nestAccessControl.UseRoles({
    resource: "EbookMarketing",
    action: "read",
    possession: "any",
  })
  async ebookMarketings(
    @graphql.Args() args: EbookMarketingFindManyArgs
  ): Promise<EbookMarketing[]> {
    return this.service.ebookMarketings(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => EbookMarketing, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "EbookMarketing",
    action: "read",
    possession: "own",
  })
  async ebookMarketing(
    @graphql.Args() args: EbookMarketingFindUniqueArgs
  ): Promise<EbookMarketing | null> {
    const result = await this.service.ebookMarketing(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => EbookMarketing)
  @nestAccessControl.UseRoles({
    resource: "EbookMarketing",
    action: "create",
    possession: "any",
  })
  async createEbookMarketing(
    @graphql.Args() args: CreateEbookMarketingArgs
  ): Promise<EbookMarketing> {
    return await this.service.createEbookMarketing({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => EbookMarketing)
  @nestAccessControl.UseRoles({
    resource: "EbookMarketing",
    action: "update",
    possession: "any",
  })
  async updateEbookMarketing(
    @graphql.Args() args: UpdateEbookMarketingArgs
  ): Promise<EbookMarketing | null> {
    try {
      return await this.service.updateEbookMarketing({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => EbookMarketing)
  @nestAccessControl.UseRoles({
    resource: "EbookMarketing",
    action: "delete",
    possession: "any",
  })
  async deleteEbookMarketing(
    @graphql.Args() args: DeleteEbookMarketingArgs
  ): Promise<EbookMarketing | null> {
    try {
      return await this.service.deleteEbookMarketing(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => EbookMarketing)
  async uploadCover(
    @graphql.Args({
      name: "file",
      type: () => GraphQLUpload,
    })
    file: FileUpload,
    @graphql.Args()
    args: EbookMarketingFindUniqueArgs
  ): Promise<EbookMarketing> {
    return await this.service.uploadCover(args, file);
  }

  @graphql.Mutation(() => EbookMarketing)
  async deleteCover(
    @graphql.Args()
    args: EbookMarketingFindUniqueArgs
  ): Promise<EbookMarketing> {
    return await this.service.deleteCover(args);
  }
}
