/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { EbookMarketingService } from "../ebookMarketing.service";
import { EbookMarketingCreateInput } from "./EbookMarketingCreateInput";
import { EbookMarketing } from "./EbookMarketing";
import { EbookMarketingFindManyArgs } from "./EbookMarketingFindManyArgs";
import { EbookMarketingWhereUniqueInput } from "./EbookMarketingWhereUniqueInput";
import { EbookMarketingUpdateInput } from "./EbookMarketingUpdateInput";

export class EbookMarketingControllerBase {
  constructor(protected readonly service: EbookMarketingService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: EbookMarketing })
  async createEbookMarketing(
    @common.Body() data: EbookMarketingCreateInput
  ): Promise<EbookMarketing> {
    return await this.service.createEbookMarketing({
      data: data,
      select: {
        category: true,
        cover: true,
        createdAt: true,
        description: true,
        id: true,
        keywords: true,
        pricing: true,
        subtitle: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [EbookMarketing] })
  @ApiNestedQuery(EbookMarketingFindManyArgs)
  async ebookMarketings(
    @common.Req() request: Request
  ): Promise<EbookMarketing[]> {
    const args = plainToClass(EbookMarketingFindManyArgs, request.query);
    return this.service.ebookMarketings({
      ...args,
      select: {
        category: true,
        cover: true,
        createdAt: true,
        description: true,
        id: true,
        keywords: true,
        pricing: true,
        subtitle: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: EbookMarketing })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async ebookMarketing(
    @common.Param() params: EbookMarketingWhereUniqueInput
  ): Promise<EbookMarketing | null> {
    const result = await this.service.ebookMarketing({
      where: params,
      select: {
        category: true,
        cover: true,
        createdAt: true,
        description: true,
        id: true,
        keywords: true,
        pricing: true,
        subtitle: true,
        title: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: EbookMarketing })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateEbookMarketing(
    @common.Param() params: EbookMarketingWhereUniqueInput,
    @common.Body() data: EbookMarketingUpdateInput
  ): Promise<EbookMarketing | null> {
    try {
      return await this.service.updateEbookMarketing({
        where: params,
        data: data,
        select: {
          category: true,
          cover: true,
          createdAt: true,
          description: true,
          id: true,
          keywords: true,
          pricing: true,
          subtitle: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: EbookMarketing })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteEbookMarketing(
    @common.Param() params: EbookMarketingWhereUniqueInput
  ): Promise<EbookMarketing | null> {
    try {
      return await this.service.deleteEbookMarketing({
        where: params,
        select: {
          category: true,
          cover: true,
          createdAt: true,
          description: true,
          id: true,
          keywords: true,
          pricing: true,
          subtitle: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
