/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { GraphQLUpload } from "graphql-upload";
import { FileUpload } from "src/storage/base/storage.types";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { PublisherInformation } from "./PublisherInformation";
import { PublisherInformationCountArgs } from "./PublisherInformationCountArgs";
import { PublisherInformationFindManyArgs } from "./PublisherInformationFindManyArgs";
import { PublisherInformationFindUniqueArgs } from "./PublisherInformationFindUniqueArgs";
import { CreatePublisherInformationArgs } from "./CreatePublisherInformationArgs";
import { UpdatePublisherInformationArgs } from "./UpdatePublisherInformationArgs";
import { DeletePublisherInformationArgs } from "./DeletePublisherInformationArgs";
import { PublisherInformationService } from "../publisherInformation.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => PublisherInformation)
export class PublisherInformationResolverBase {
  constructor(
    protected readonly service: PublisherInformationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "PublisherInformation",
    action: "read",
    possession: "any",
  })
  async _publisherInformationsMeta(
    @graphql.Args() args: PublisherInformationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [PublisherInformation])
  @nestAccessControl.UseRoles({
    resource: "PublisherInformation",
    action: "read",
    possession: "any",
  })
  async publisherInformations(
    @graphql.Args() args: PublisherInformationFindManyArgs
  ): Promise<PublisherInformation[]> {
    return this.service.publisherInformations(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => PublisherInformation, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "PublisherInformation",
    action: "read",
    possession: "own",
  })
  async publisherInformation(
    @graphql.Args() args: PublisherInformationFindUniqueArgs
  ): Promise<PublisherInformation | null> {
    const result = await this.service.publisherInformation(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => PublisherInformation)
  @nestAccessControl.UseRoles({
    resource: "PublisherInformation",
    action: "create",
    possession: "any",
  })
  async createPublisherInformation(
    @graphql.Args() args: CreatePublisherInformationArgs
  ): Promise<PublisherInformation> {
    return await this.service.createPublisherInformation({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => PublisherInformation)
  @nestAccessControl.UseRoles({
    resource: "PublisherInformation",
    action: "update",
    possession: "any",
  })
  async updatePublisherInformation(
    @graphql.Args() args: UpdatePublisherInformationArgs
  ): Promise<PublisherInformation | null> {
    try {
      return await this.service.updatePublisherInformation({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => PublisherInformation)
  @nestAccessControl.UseRoles({
    resource: "PublisherInformation",
    action: "delete",
    possession: "any",
  })
  async deletePublisherInformation(
    @graphql.Args() args: DeletePublisherInformationArgs
  ): Promise<PublisherInformation | null> {
    try {
      return await this.service.deletePublisherInformation(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => PublisherInformation)
  async uploadLogo(
    @graphql.Args({
      name: "file",
      type: () => GraphQLUpload,
    })
    file: FileUpload,
    @graphql.Args()
    args: PublisherInformationFindUniqueArgs
  ): Promise<PublisherInformation> {
    return await this.service.uploadLogo(args, file);
  }

  @graphql.Mutation(() => PublisherInformation)
  async deleteLogo(
    @graphql.Args()
    args: PublisherInformationFindUniqueArgs
  ): Promise<PublisherInformation> {
    return await this.service.deleteLogo(args);
  }
}
