/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request, Response } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { FileInterceptor } from "@nestjs/platform-express";
import { PublisherInformationService } from "../publisherInformation.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PublisherInformationCreateInput } from "./PublisherInformationCreateInput";
import { PublisherInformation } from "./PublisherInformation";
import { PublisherInformationFindManyArgs } from "./PublisherInformationFindManyArgs";
import { PublisherInformationWhereUniqueInput } from "./PublisherInformationWhereUniqueInput";
import { PublisherInformationUpdateInput } from "./PublisherInformationUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PublisherInformationControllerBase {
  constructor(
    protected readonly service: PublisherInformationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PublisherInformation })
  @nestAccessControl.UseRoles({
    resource: "PublisherInformation",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createPublisherInformation(
    @common.Body() data: PublisherInformationCreateInput
  ): Promise<PublisherInformation> {
    return await this.service.createPublisherInformation({
      data: data,
      select: {
        about: true,
        createdAt: true,
        id: true,
        logo: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [PublisherInformation] })
  @ApiNestedQuery(PublisherInformationFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "PublisherInformation",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async publisherInformations(
    @common.Req() request: Request
  ): Promise<PublisherInformation[]> {
    const args = plainToClass(PublisherInformationFindManyArgs, request.query);
    return this.service.publisherInformations({
      ...args,
      select: {
        about: true,
        createdAt: true,
        id: true,
        logo: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PublisherInformation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PublisherInformation",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async publisherInformation(
    @common.Param() params: PublisherInformationWhereUniqueInput
  ): Promise<PublisherInformation | null> {
    const result = await this.service.publisherInformation({
      where: params,
      select: {
        about: true,
        createdAt: true,
        id: true,
        logo: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PublisherInformation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PublisherInformation",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updatePublisherInformation(
    @common.Param() params: PublisherInformationWhereUniqueInput,
    @common.Body() data: PublisherInformationUpdateInput
  ): Promise<PublisherInformation | null> {
    try {
      return await this.service.updatePublisherInformation({
        where: params,
        data: data,
        select: {
          about: true,
          createdAt: true,
          id: true,
          logo: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PublisherInformation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PublisherInformation",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePublisherInformation(
    @common.Param() params: PublisherInformationWhereUniqueInput
  ): Promise<PublisherInformation | null> {
    try {
      return await this.service.deletePublisherInformation({
        where: params,
        select: {
          about: true,
          createdAt: true,
          id: true,
          logo: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Put(":id/logo")
  @common.UseInterceptors(FileInterceptor("file"))
  @swagger.ApiConsumes("multipart/form-data")
  @swagger.ApiBody({
    schema: {
      type: "object",

      properties: {
        file: {
          type: "string",
          format: "binary",
        },
      },
    },
  })
  @swagger.ApiParam({
    name: "id",
    type: "string",
    required: true,
  })
  @swagger.ApiCreatedResponse({
    type: PublisherInformation,
    status: "2XX",
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  async uploadLogo(
    @common.Param()
    params: PublisherInformationWhereUniqueInput,
    @common.UploadedFile()
    file: Express.Multer.File
  ): Promise<PublisherInformation> {
    return this.service.uploadLogo(
      {
        where: params,
      },
      Object.assign(file, {
        filename: file.originalname,
      })
    );
  }

  @common.Get(":id/logo")
  @swagger.ApiParam({
    name: "id",
    type: "string",
    required: true,
  })
  @swagger.ApiOkResponse({
    type: common.StreamableFile,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  async downloadLogo(
    @common.Param()
    params: PublisherInformationWhereUniqueInput,
    @common.Res({
      passthrough: true,
    })
    res: Response
  ): Promise<common.StreamableFile> {
    const result = await this.service.downloadLogo({
      where: params,
    });

    if (result === null) {
      throw new errors.NotFoundException(
        "No resource was found for ",
        JSON.stringify(params)
      );
    }

    res.setHeader(
      "Content-Disposition",
      `attachment; filename=${result.filename}`
    );
    res.setHeader("Content-Type", result.mimetype);
    return result.stream;
  }

  @common.Delete(":id/logo")
  @swagger.ApiOkResponse({
    type: PublisherInformation,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  async deleteLogo(
    @common.Param()
    params: PublisherInformationWhereUniqueInput
  ): Promise<PublisherInformation> {
    return this.service.deleteLogo({
      where: params,
    });
  }
}
