/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { GraphQLUpload } from "graphql-upload";
import { FileUpload } from "src/storage/base/storage.types";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AuthorInformation } from "./AuthorInformation";
import { AuthorInformationCountArgs } from "./AuthorInformationCountArgs";
import { AuthorInformationFindManyArgs } from "./AuthorInformationFindManyArgs";
import { AuthorInformationFindUniqueArgs } from "./AuthorInformationFindUniqueArgs";
import { CreateAuthorInformationArgs } from "./CreateAuthorInformationArgs";
import { UpdateAuthorInformationArgs } from "./UpdateAuthorInformationArgs";
import { DeleteAuthorInformationArgs } from "./DeleteAuthorInformationArgs";
import { AuthorInformationService } from "../authorInformation.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => AuthorInformation)
export class AuthorInformationResolverBase {
  constructor(
    protected readonly service: AuthorInformationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "AuthorInformation",
    action: "read",
    possession: "any",
  })
  async _authorInformationsMeta(
    @graphql.Args() args: AuthorInformationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [AuthorInformation])
  @nestAccessControl.UseRoles({
    resource: "AuthorInformation",
    action: "read",
    possession: "any",
  })
  async authorInformations(
    @graphql.Args() args: AuthorInformationFindManyArgs
  ): Promise<AuthorInformation[]> {
    return this.service.authorInformations(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => AuthorInformation, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "AuthorInformation",
    action: "read",
    possession: "own",
  })
  async authorInformation(
    @graphql.Args() args: AuthorInformationFindUniqueArgs
  ): Promise<AuthorInformation | null> {
    const result = await this.service.authorInformation(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => AuthorInformation)
  @nestAccessControl.UseRoles({
    resource: "AuthorInformation",
    action: "create",
    possession: "any",
  })
  async createAuthorInformation(
    @graphql.Args() args: CreateAuthorInformationArgs
  ): Promise<AuthorInformation> {
    return await this.service.createAuthorInformation({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => AuthorInformation)
  @nestAccessControl.UseRoles({
    resource: "AuthorInformation",
    action: "update",
    possession: "any",
  })
  async updateAuthorInformation(
    @graphql.Args() args: UpdateAuthorInformationArgs
  ): Promise<AuthorInformation | null> {
    try {
      return await this.service.updateAuthorInformation({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => AuthorInformation)
  @nestAccessControl.UseRoles({
    resource: "AuthorInformation",
    action: "delete",
    possession: "any",
  })
  async deleteAuthorInformation(
    @graphql.Args() args: DeleteAuthorInformationArgs
  ): Promise<AuthorInformation | null> {
    try {
      return await this.service.deleteAuthorInformation(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => AuthorInformation)
  async uploadImage(
    @graphql.Args({
      name: "file",
      type: () => GraphQLUpload,
    })
    file: FileUpload,
    @graphql.Args()
    args: AuthorInformationFindUniqueArgs
  ): Promise<AuthorInformation> {
    return await this.service.uploadImage(args, file);
  }

  @graphql.Mutation(() => AuthorInformation)
  async deleteImage(
    @graphql.Args()
    args: AuthorInformationFindUniqueArgs
  ): Promise<AuthorInformation> {
    return await this.service.deleteImage(args);
  }
}
